if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval $(dbus-launch --exit-with-session --sh-syntax)
fi
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environmnet >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi

feh --bg-scale ~/.config/oxwm/wallpaper.png &
picom  & redshift -l 40.500664664:-80.067833062 &
exec oxwm
