general {
    colors = true
    interval = 5
    color_good     = "#14C72E"
    color_degraded = "#e0af68"
    color_bad      = "#f7768e"
}

order += "time"
order += "cpu_usage"
order += "memory"
order += "battery 0"

time {
    format = "%a, %b %d - %-I:%M %p"
}

cpu_usage {
    format = "CPU: %usage"
    max_threshold = 95
    degraded_threshold = 90
}

memory {
    format = "Ram: %used / %total"
    unit = "GiB"
    threshold_degraded = "1G"
    format_degraded = "Ram: LOW"
}

battery 0 {
    format = "Bat: %percentage"
    format_down = "No Battery"
    status_chr = "⚡ Bat: %percentage"
    status_bat = "Bat: %percentage"
    status_unk = "? Bat: %percentage"
    status_full = "Bat: %percentage"
    path = "/sys/class/power_supply/BAT%d/uevent"
    low_threshold = 10
}
